In [1]:
import numpy as np
from numpy import genfromtxt
data = genfromtxt('bank_note_data.txt', delimiter=',')

In [2]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [3]:
labels = data[:,4]

In [4]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [5]:
features = data[:,0:4]

In [6]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [7]:
X = features
y = labels

### We have all the data imported now. What we need to do next is to split it to training and test set. 
### A good split is 33.33% for test and 66.66% for training

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [10]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [12]:
X_train.size

3676

In [13]:
X_test.size

1812

In [14]:
X.size

5488

### There is a chance for the data to be in different range. We need everything in similar range for learning
### We are going to standardise the data now

In [16]:
from sklearn.preprocessing import MinMaxScaler
scaler_object = MinMaxScaler()    #We have created a scaler object

In [17]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [18]:
scaled_X_train = scaler_object.transform(X_train)

In [19]:
scaled_X_test = scaler_object.transform(X_test)

In [20]:
scaled_X_train.max()

1.0000000000000002

In [21]:
scaled_X_test.max()

1.02679563427227

In [22]:
scaled_X_train.min()

0.0

In [23]:
scaled_X_test.min()

-0.0010694864308909147

### Building a simple neural network with Keras

In [25]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [26]:
# Creates model
model = Sequential()
# 8 Neurons, expects input of 4 features. 
# Play around with the number of neurons!!
model.add(Dense(4, input_dim=4, activation='relu'))
# Add another Densely Connected layer (every neuron connected to every neuron in the next layer)
model.add(Dense(8, activation='relu'))
# Adding one more layer

# Last layer simple sigmoid function to output 0 or 1 (our label)
model.add(Dense(1, activation='sigmoid'))

In [27]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [29]:
# Play around with number of epochs as well!
model.fit(scaled_X_train,y_train,epochs=50, verbose=2)

Epoch 1/50
 - 0s - loss: 0.6718 - acc: 0.6050
Epoch 2/50
 - 0s - loss: 0.6664 - acc: 0.6235
Epoch 3/50
 - 0s - loss: 0.6601 - acc: 0.6420
Epoch 4/50
 - 0s - loss: 0.6538 - acc: 0.6453
Epoch 5/50
 - 0s - loss: 0.6472 - acc: 0.6540
Epoch 6/50
 - 0s - loss: 0.6397 - acc: 0.6659
Epoch 7/50
 - 0s - loss: 0.6319 - acc: 0.6681
Epoch 8/50
 - 0s - loss: 0.6242 - acc: 0.6692
Epoch 9/50
 - 0s - loss: 0.6157 - acc: 0.6659
Epoch 10/50
 - 0s - loss: 0.6074 - acc: 0.6594
Epoch 11/50
 - 0s - loss: 0.5969 - acc: 0.6649
Epoch 12/50
 - 0s - loss: 0.5825 - acc: 0.6681
Epoch 13/50
 - 0s - loss: 0.5589 - acc: 0.7127
Epoch 14/50
 - 0s - loss: 0.5383 - acc: 0.7291
Epoch 15/50
 - 0s - loss: 0.5183 - acc: 0.7465
Epoch 16/50
 - 0s - loss: 0.4959 - acc: 0.7650
Epoch 17/50
 - 0s - loss: 0.4736 - acc: 0.7661
Epoch 18/50
 - 0s - loss: 0.4498 - acc: 0.7911
Epoch 19/50
 - 0s - loss: 0.4263 - acc: 0.8041
Epoch 20/50
 - 0s - loss: 0.4026 - acc: 0.8183
Epoch 21/50
 - 0s - loss: 0.3786 - acc: 0.8357
Epoch 22/50
 - 0s - lo

In [30]:
model.predict_classes(scaled_X_test)

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    

### Performance Evaluvation

In [31]:
model.metrics_names

['loss', 'acc']

In [32]:
model.evaluate(x=scaled_X_test,y=y_test)

453/453 [==============================] - 0s 282us/step


[0.08943118491347789, 0.9668874172185431]

In [33]:
from sklearn.metrics import confusion_matrix,classification_report

In [34]:
predictions = model.predict_classes(scaled_X_test)
confusion_matrix(y_test,predictions)

array([[254,   3],
       [ 12, 184]])

In [35]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.95      0.99      0.97       257
        1.0       0.98      0.94      0.96       196

avg / total       0.97      0.97      0.97       453



In [36]:
### Saving Model 

In [37]:
model.save('vishnusfirstmodel.h5')

In [38]:
from keras.models import load_model

In [40]:
newmodel = load_model('vishnusfirstmodel.h5')

In [41]:
newmodel.predict_classes(X_test)

array([[0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    