In [1]:
import numpy as np

In [2]:
myList = [1,2,3]

In [3]:
type(myList)

list

In [4]:
myArray = np.array(myList) #converts list to numpy array

In [5]:
type(myArray)

numpy.ndarray

In [6]:
np.arange(0, 10) #arange gives a list of values with a given interval. Here it prints 0 till 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 10, 2) #here 2 is the interval. So it returns elemnts with 2 as interval

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(shape=(10,5)) #shape is used to give rows and columns. Numpy creates the float by default.

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
type(0)

int

In [11]:
type(0.0)

float

In [12]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.ones((3,4)) #shape is not required. We can do like this as well

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.random.seed(101)
arr1 = np.random.randint(0, 100, 10)

In [16]:
arr1

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [17]:
arr2 = np.random.randint(0, 100, 10)

In [18]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [19]:
arr1.max() #returns the max value in an array

95

In [20]:
arr1.argmax() #returns the location of the max value

0

In [21]:
arr1.argmin()

7

In [23]:
arr1.mean() #calculates the mean

60.8

In [25]:
arr1.shape  #here if we see, there is no second argument in shape. This is because this is a vector

(10,)

In [27]:
arr1.reshape((2,5)) #we cannot give a shape like 2,3 here as 10 elements cannot be split like that. It will give error

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [28]:
mat = np.arange(0, 100).reshape(10, 10)

In [29]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [30]:
mat.shape

(10, 10)

In [31]:
row = 3
col = 5
mat[row, col]

35

In [33]:
mat[:,1]   #this return all elements in colum 1

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [34]:
mat[:,1].shape

(10,)

In [35]:
mat[2,:]  #this returns all elements in row 1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [36]:
mat[2,:].shape

(10,)

In [37]:
mat[3:8,2:7]  #slicing another matrix from the original matrix

array([[32, 33, 34, 35, 36],
       [42, 43, 44, 45, 46],
       [52, 53, 54, 55, 56],
       [62, 63, 64, 65, 66],
       [72, 73, 74, 75, 76]])

In [38]:
mat1 = mat.copy()  #creates a new matrix called mat1 from mat

In [39]:
mat1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [40]:
mat1[3:8,2:7] = 0  #this will make all elements of this porting zero.

In [41]:
mat1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31,  0,  0,  0,  0,  0, 37, 38, 39],
       [40, 41,  0,  0,  0,  0,  0, 47, 48, 49],
       [50, 51,  0,  0,  0,  0,  0, 57, 58, 59],
       [60, 61,  0,  0,  0,  0,  0, 67, 68, 69],
       [70, 71,  0,  0,  0,  0,  0, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])